# Generated by Django 3.2.5 on 2021-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis_reg_form', models.CharField(max_length=40, verbose_name='форма бизнеса')),
                ('taxation_system', models.CharField(max_length=40, verbose_name='система налогообложения')),
                ('article', models.PositiveIntegerField(blank=True, verbose_name='артикул товара')),
                ('date_start', models.DateField(verbose_name='дата начала')),
                ('date_end', models.DateField(verbose_name='дата конца')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('article', models.PositiveIntegerField(verbose_name='артикул товара')),
                ('date_sales', models.DateField(verbose_name='дата продажи')),
                ('product_price', models.FloatField(verbose_name='цена за единицу')),
                ('product_count', models.PositiveIntegerField(verbose_name='количество')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('article', models.PositiveIntegerField(verbose_name='артикул товара')),
                ('date_sales', models.DateField(verbose_name='дата продажи')),
                ('product_price', models.FloatField(verbose_name='цена за единицу')),
                ('product_count', models.PositiveIntegerField(verbose_name='количество')),
            ],
        ),
    ]
