# Generated by Django 3.2.5 on 2021-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accinfo',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='прибыль'),
            preserve_default=False,
        ),
    ]
