# Generated by Django 3.2.5 on 2021-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_accinfo_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accinfo',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='артикул товара'),
        ),
        migrations.AlterField(
            model_name='accinfo',
            name='profit',
            field=models.FloatField(verbose_name='прибыль'),
        ),
    ]
